# Generated by Django 5.2.4 on 2025-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0002_department_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
