# Generated by Django 5.2.4 on 2025-07-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0004_faculty_subjectslist_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
