# Generated by Django 5.2.4 on 2025-07-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0006_attendanceview_alter_faculty_faculty_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceView',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusapp.faculty'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
