# Generated by Django 5.2.4 on 2025-07-21 04:49

import campusapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0007_delete_attendanceview_alter_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_date',
            field=models.DateField(default=campusapp.models.AssignmentSubmission.get_current_date),
        ),
    ]
