# Generated by Django 5.2.4 on 2025-07-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0008_assignmentsubmission_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='campusapp.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('resource_file', models.FileField(upload_to='')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusapp.subjectslist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusapp.faculty')),
            ],
        ),
    ]
